name: Build CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./challenge-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get ./
      - name: Build
        run: GOOS=linux GOARCH=arm64 go build
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: devonberta/devops-challenge:latest
          context: ./challenge-1  
          file: ./challenge-1/Dockerfile  